"""A synthetic market, so the data layer can be tested without the network.

The prices are generated by a GARCH-like process: volatility persists, spikes,
and decays. That matters because it plants the exact relationship the model is
meant to find - if a test on this data cannot recover "trailing volatility
predicts future volatility", the code is broken, not the market.

The generator also produces the failure modes deliberately, so the checks that
catch them have something to catch: an unadjusted split, a delisted ticker that
stops mid-history, and a newly listed one with almost no history.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

TICKERS = [f"T{i:03d}" for i in range(1, 41)]

TRADING_DAYS = 252
BASE_VOL = 0.22          # annualised
VOL_PERSISTENCE = 0.94   # how much of yesterday's vol carries into today
VOL_OF_VOL = 0.14


def _garch_path(n: int, rng: np.random.Generator, base: float) -> np.ndarray:
    """Daily volatility that clusters, the way real volatility does."""
    daily_base = base / np.sqrt(TRADING_DAYS)
    log_v = np.log(daily_base)
    target = log_v
    out = np.empty(n)
    for i in range(n):
        log_v = (VOL_PERSISTENCE * log_v + (1 - VOL_PERSISTENCE) * target
                 + rng.normal(0, VOL_OF_VOL))
        out[i] = np.exp(log_v)
    return out


def make_prices(tickers=None, days: int = 2600, seed: int = 1729,
                with_splits: bool = True, with_delistings: bool = True
                ) -> pd.DataFrame:
    """Daily bars in the same shape `prices.load` returns."""
    rng = np.random.default_rng(seed)
    tickers = list(tickers or TICKERS)
    dates = pd.bdate_range("2014-01-02", periods=days)

    rows = []
    for k, t in enumerate(tickers):
        n = days
        start_at = 0
        if with_delistings and k % 13 == 5:
            n = days // 2               # leaves the index halfway through
        if k % 11 == 7:
            start_at = days - 200       # only listed recently

        vol = _garch_path(n, rng, BASE_VOL * float(rng.uniform(0.6, 1.9)))
        # A small positive drift, deliberately far too small to be forecastable
        # from anything in the data - which is the honest situation.
        rets = rng.normal(0.0003, 1.0, n) * vol
        price = 40 * float(rng.uniform(0.5, 5)) * np.exp(np.cumsum(rets))

        split_at = None
        if with_splits and k % 17 == 3 and n > 400:
            # An UNADJUSTED 2-for-1. The audit must notice this.
            split_at = n // 2
            price[split_at:] /= 2.0

        for i in range(start_at, n):
            close = float(price[i])
            wobble = float(vol[i]) * close
            rows.append({
                "date": dates[i],
                "ticker": t,
                "open": close * (1 + float(rng.normal(0, 0.003))),
                "high": close + abs(float(rng.normal(0, wobble))),
                "low": close - abs(float(rng.normal(0, wobble))),
                "close": close,
                "volume": float(rng.integers(200_000, 9_000_000)),
                "source": "fixture",
            })

    df = pd.DataFrame(rows)
    return df.sort_values(["ticker", "date"]).reset_index(drop=True)


def make_market(days: int = 2600, seed: int = 5150) -> pd.DataFrame:
    """Index and volatility references, in the same shape as the real ones."""
    rng = np.random.default_rng(seed)
    dates = pd.bdate_range("2014-01-02", periods=days)
    rows = []
    for t, base in (("SPY", 0.16), ("QQQ", 0.20), ("IWM", 0.22)):
        vol = _garch_path(days, rng, base)
        px = 200 * np.exp(np.cumsum(rng.normal(0.0004, 1.0, days) * vol))
        for i in range(days):
            c = float(px[i])
            rows.append({"date": dates[i], "ticker": t, "open": c, "high": c * 1.004,
                         "low": c * 0.996, "close": c, "volume": 5e7,
                         "source": "fixture"})
    # A VIX that tracks the index's own volatility, as the real one does.
    spy_vol = _garch_path(days, rng, 0.16)
    for i in range(days):
        v = float(spy_vol[i]) * np.sqrt(TRADING_DAYS) * 100 * 1.1
        rows.append({"date": dates[i], "ticker": "^VIX", "open": v, "high": v,
                     "low": v, "close": v, "volume": 0.0, "source": "fixture"})
    return pd.DataFrame(rows).sort_values(["ticker", "date"]).reset_index(drop=True)


def make_earnings(tickers=None, seed: int = 4242) -> pd.DataFrame:
    """Quarterly report dates, roughly 90 days apart with real-world jitter."""
    rng = np.random.default_rng(seed)
    tickers = list(tickers or TICKERS)
    rows = []
    for t in tickers:
        d = pd.Timestamp("2014-02-05") + pd.Timedelta(days=int(rng.integers(0, 89)))
        while d < pd.Timestamp("2025-01-01"):
            rows.append({"ticker": t, "date": d})
            d = d + pd.Timedelta(days=int(90 + rng.integers(-6, 7)))
    return pd.DataFrame(rows)


def make_universe_history(tickers=None, seed: int = 99) -> pd.DataFrame:
    """Membership that actually changes, so survivorship logic has work to do."""
    rng = np.random.default_rng(seed)
    tickers = list(tickers or TICKERS)
    dates = pd.bdate_range("2014-01-02", periods=2600, freq="C")[::260]
    rows, members = [], list(tickers[:30])
    for d in dates:
        rows.append({"date": d, "members": sorted(members), "n": len(members)})
        # One out, one in, so the count stays put and the names do not.
        if len(members) > 5 and len(members) < len(tickers):
            members.pop(int(rng.integers(0, len(members))))
            spare = [t for t in tickers if t not in members]
            if spare:
                members.append(spare[int(rng.integers(0, len(spare)))])
    return pd.DataFrame(rows)
